export default [
  {
    id: 1,
    dogImage: "images/dog1.jpg",
    title: "First Dog",
    bannerImage: "images/dog1.jpg",
    taskDate: "11-05-2023",
    summary: "May 11",
  },
  {
    id: 2,
    dogImage: "images/dog2.jpg",
    title: "Second Dog",
    bannerImage: "images/dog2.jpg",
    taskDate: "11-06-2023",
    summary: "June 11",
  },
  {
    id: 3,
    dogImage: "images/dog3.jpg",
    title: "Third Dog",
    bannerImage: "images/dog3.jpg",
    taskDate: "11-07-2023",
    summary: "July 11",
  },
  ,
  {
    id: 4,
    dogImage: "images/dog4.jpg",
    title: "Fourth Dog",
    bannerImage: "images/dog4.jpg",
    taskDate: "11-05-2023",
    summary: "Mar 11",
  },
  {
    id: 5,
    dogImage: "images/dog5.jpg",
    title: "Fifth Dog",
    bannerImage: "images/dog5.jpg",
    taskDate: "11-05-2023",
    summary: "Mar 11",
  },
  {
    id: 6,
    dogImage: "images/dog6.jpg",
    title: "Sixth Dog",
    bannerImage: "images/dog6.jpg",
    taskDate: "11-05-2023",
    summary: "Mar 11",
  },
];
